### PR TITLE
Apply ACE editor to CF Templates forms helper

### PR DESCRIPTION
**Pull request by Joeper214**
### Goals of this PR

Apply ace editor on  cf_template by the ff:

- [x] creating
- [x] editing
- [x] Displaying

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Review and Merge PR. @pocke  Thanks!

**Comment by pocke** [comment]
I will start a review

**Comment by pocke** [comment]
```
  1) Users::SessionsController#check_mfa_key when receive email, password and MFA-token when verify success should be success

     Failure/Error: expect(response).to be_success,

       expected success, but response code is 302, response body is "<html><body>You are being <a href=\"http://test.host/users/sign_in?lang=ja\">redirected</a>.</body></html>"

     # ./spec/support/controller_macros.rb:35:in `block in should_be_success'
```

**Comment by pocke** [comment]
LGTM!

**Pull request merged**
