### PR TITLE
Browserify TypeScript

### PR DESCRIPTION
**Pull request by pocke**
Browserify

- [x] server_status.ts
- [x] modal.ts

Update process
----

```sh
cd frontend/
gulp ts
```

Trouble shooting
------

```sh
bundle exec rake tmp:cache:clear
rm -rf tmp/
mkdir tmp/pids/ -p
```

### CODE REVIEW

**Comment by pocke** [comment]
`git diff -b`を使用すると、Diffが見やすくなります

**Comment by pocke** [comment]
Test is broken!

**Comment by Joeper214** [comment]
:scream:

**Comment by pocke** [comment]
Use relative path, maybe solve this problem.
but browserify-rails doesn't work now...

**Comment by Joeper214** [comment]
Did you tried importing a browserify file to another browserify file?

**Comment by pocke** [comment]
No, I tried importing file under `frontend/dest/` directly.
I think cause is this

**Comment by Joeper214** [comment]
Yeah. maybe. did you tried to import the file under `frontend/src` ?

**Comment by Joeper214** [comment]
Test is fine. :tada:

**Comment by pocke** [comment]
:tada:

but doesn't work sync button...

**Comment by Joeper214** [comment]
can I see the line on how sync works?

**Comment by pocke** [comment]
https://github.com/skyarch-networks/skyhopper/blob/browserify-typescript/frontend/src/users_admin.ts#L44

**Comment by pocke** [comment]
```ruby
 # Paths, that should be browserified. We browserify everything, that
  # matches (===) one of the paths. So you will most likely put lambdas
  # regexes in here.
  #
  # By default only files in /app and /node_modules are browserified,
  # vendor stuff is normally not made for browserification and may stop
  # working.
  config.browserify_rails.paths << /vendor\/assets\/javascripts\/module\.js/
```

I used this, but doesn't work...

**Comment by Joeper214** [comment]
It says in this error.

no_confirm

**Comment by Joeper214** [comment]
Maybe this can help. https://www.npmjs.com/package/tsify  @pocke

**Comment by Joeper214** [comment]
It supports browserify on typescript.

**Comment by pocke** [comment]
I removed cache, sync button begins working!

**Comment by pocke** [comment]
https://github.com/browserify-rails/browserify-rails#clear-the-asset-pipeline-cache

>  rake tmp:cache:clear
> rm -rf ./tmp (when in the root directory of the Rails project)

**Comment by Joeper214** [comment]
I see. that's a relief.

**Comment by pocke** [comment]
Thanks!

**Comment by Joeper214** [comment]
this line removed my `sidekiq.pid` .  :(

**Comment by Joeper214** [comment]
`rm -rf ./tmp (when in the root directory of the Rails project)`

**Comment by pocke** [comment]
Please `mkdir tmp/pids/ -p` and restart server.

**Comment by Joeper214** [comment]
It works!. thanks.

**Comment by pocke** [comment]
@Joeper214 please review and merge it :bow:

**Comment by Joeper214** [comment]
This line still doesn't work. for me.
no_confirm

Can I see the workflow?
is it 

````
rake tmp:cache:clear
rm -rf ./tmp (when in the root directory of the Rails project)
```

Then,

```
cd frontend
npm i
gulp tsd
gulp ts
``` ?

**Comment by pocke** [comment]
I think the above workflow is ok...

Did you restart rails server ?

**Comment by Joeper214** [comment]
yes.

**Comment by Joeper214** [comment]
It works now. thanks!

**Comment by pocke** [comment]
:+1:

**Comment by Joeper214** [comment]
LGTM! I'll merge once test is done.

**Comment by pocke** [comment]
Thanks! :dancers:

**Pull request merged**
