### PR TITLE
Improve alert in project

### PR DESCRIPTION
**Pull request by root-beer**

### CODE REVIEW

**Comment by root-beer** [comment]
Please review and merge PR. @Joeper214 :bow:

**Comment by Joeper214** [comment]
Test is broken.

**Comment by root-beer** [comment]
Please review and merge PR. @Joeper214 🙇

**Comment by Joeper214** [comment]
はい。I'll review now.

**Comment by Joeper214** [comment]
LGTM! Thanks.

**Comment by root-beer** [comment]
Thanks! :bow:

**Pull request merged**
