### PR TITLE
hotfix for ace flodding

### PR DESCRIPTION
**Pull request by Joeper214**

### CODE REVIEW

**Comment by pocke** [comment]
Test failed... I'll investigate

**Comment by pocke** [comment]
Segmentation fault! https://travis-ci.org/skyarch-networks/skyhopper/jobs/82883334#L1469

**Comment by Joeper214** [comment]
Okay. I checked it out from develop branch.

**Comment by pocke** [comment]
I think this is ruby bug

**Comment by Joeper214** [comment]
How to fix it?

**Comment by Joeper214** [comment]
I see. :dancer:   I only touch JS code.

**Comment by pocke** [comment]
Hmm... I retried test, but still failed...

**Comment by Joeper214** [comment]
This is getting weird. :confounded:

**Comment by pocke** [comment]
:+1:

**Comment by Joeper214** [comment]
Thanks.

**Pull request merged**
