### PR TITLE
[WIP] User mgt index

### PR DESCRIPTION
**Pull request by Joeper214**
### Goal in this PR
- [x] Apply SSP on User manangement Index
- [x] UI enhancement

### CODE REVIEW

**Comment by Joeper214** [comment]
The <code> //=require user_index </code> is not working even though I was running this. <code> gulp ts </code>

Any thoughts @pocke  san?

**Comment by pocke** [comment]
Please try `//= require user_index`.
Add space into between `//=` and `require`

**Comment by Joeper214** [comment]
Please merge this PR after reviewing it. Thanks!.

**Comment by pocke** [comment]
@root-beer Please review instead of me!

**Comment by pocke** [comment]
Can you try to replace `app/assets/javascripts/modules/md5.js` to npm package?

**Comment by Joeper214** [comment]
:+1:

**Comment by root-beer** [comment]
Is Serverspec Logs not working?

**Comment by Joeper214** [comment]
Yes. That button is not functional yet. it will be on another PR.

**Comment by Joeper214** [comment]
Because this PR is for user_mange index only. sorry

**Comment by root-beer** [comment]
I understand it.

**Comment by root-beer** [comment]
Could you format the value of "Last signed in at" such as "2015-09-04 15:39:13 +0900"

**Comment by Joeper214** [comment]
:+1:

**Comment by Joeper214** [comment]
What formatting do you mean? like this September 1, 2015 at 15:29?

**Comment by Joeper214** [comment]
Because the current formatting is like this. 
last

**Comment by root-beer** [comment]
This is the previous format. I like this.
default

**Comment by pocke** [comment]
https://github.com/skyarch-networks/skyhopper/blob/develop/app/assets/javascripts/infrastructures.js#L52-L55

**Comment by Joeper214** [comment]
Thanks!

**Comment by Joeper214** [comment]
Is this okay @root-beer san?

lastlog

**Comment by root-beer** [comment]
It seems good. Thanks!

**Comment by Joeper214** [comment]
Please merge it if you are done reviewing. thanks.

**Comment by root-beer** [comment]
I think that need to describe it to frontend/package.json to use md5 module.

**Comment by Joeper214** [comment]
:+1:  okay. I'll try.

**Comment by Joeper214** [comment]
done. :)

**Comment by root-beer** [comment]
Thanks!

**Pull request merged**
