### PR TITLE
Display custom error page on bad gateway

### PR DESCRIPTION
**Pull request by root-beer**
ref: https://skyarch.backlog.jp/view/NC-670

### CODE REVIEW

**Comment by root-beer** [comment]
Please review and merge PR. @Joeper214 :bow:

**Comment by Joeper214** [comment]
I'll review now.

**Comment by Joeper214** [comment]
Can I append English message?

**Comment by root-beer** [comment]
よろしくお願いします :bow:

**Comment by Joeper214** [comment]
LGTM! Thanks.

**Pull request merged**
