### PR TITLE
[WIP] Search user scope

### PR DESCRIPTION
**Pull request by Joeper214**
### Fix for UI search in admin index page

https://skyarch.backlog.jp/view/NC-510#comment-1125208708

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Merge PR. After reviewing it. thanks!

**Comment by pocke** [comment]
I fix conflict

**Comment by Joeper214** [comment]
Thanks!

**Comment by pocke** [comment]
Merged. Thanks :+1:

**Pull request merged**
