### PR TITLE
Offline-mode

### PR DESCRIPTION
**Pull request by Joeper214**
UI Helper when there is no internet connection. 

ref: http://github.hubspot.com/offline/

### CODE REVIEW

**Comment by Joeper214** [comment]
Please review and Merge PR. @root-beer . Thanks!. :bow:

**Comment by root-beer** [comment]
:+1:

**Comment by Joeper214** [comment]
Thanks!. :bow: Did you tried it on your instance? @root-beer

**Comment by root-beer** [comment]
@Joeper214 Yes! It works.

**Comment by Joeper214** [comment]
:+1:

**Pull request merged**
