### PR TITLE
Operation Scheduler SSP

### PR DESCRIPTION
**Pull request by Joeper214**
### Goal of PR

- [x] for operation scheduler 
       * searchable
       * table sorting
       * pagination
- [x] re-fetching of events during save

### CODE REVIEW

**Comment by Joeper214** [comment]
this is Ready for review.  @pocke . :bow:

**Comment by pocke** [comment]
OK, I'll review

**Comment by Joeper214** [comment]
Thanks!.

**Comment by pocke** [comment]
LGTM :+1:

**Comment by Joeper214** [comment]
Please merge. :bow:  Thank you!

**Pull request merged**
