### PR TITLE
[WIP]Serverspec index

### PR DESCRIPTION
**Pull request by Joeper214**
### Serverspec index page

* Sorting
* Searching
* Pagination

### CODE REVIEW

**Comment by Joeper214** [comment]
please merge it if you are done reviewing this code.

**Comment by pocke** [comment]
Conflict occurs.
Please solve conflict? I'll merge it after conflict is solved.

**Comment by pocke** [comment]
Thanks!

**Comment by Joeper214** [comment]
:+1:

**Pull request merged**
