### PR TITLE
Select arguments in Serverspec generator page

### PR DESCRIPTION
**Pull request by pocke**
Goal
-------

- [x] Select arguments
  - [x] get data
  - [x] UI
- [x] Select chains
  - [x] get data
  - [x] UI
  - [x] make optional

### CODE REVIEW

**Comment by pocke** [comment]
@Joeper214 Please review and merge it. :bow:

**Comment by Joeper214** [comment]
:+1:

**Comment by Joeper214** [comment]
LGTM!

**Comment by Joeper214** [comment]
THANKS!

**Comment by pocke** [comment]
Thanks! :cat:

**Pull request merged**
