### PR TITLE
NC-534

### PR DESCRIPTION
**Pull request by Joeper214**
- Reflect ANSI terminal character color/highlighting

### CODE REVIEW

**Comment by Joeper214** [comment]
Please review and Merge PR. @root-beer

**Comment by root-beer** [comment]
White letters are hard to read.

**Comment by Joeper214** [comment]
Is this better?

screen shot 2017-05-02 at 14 39 56

**Comment by root-beer** [comment]
Thanks! 😆

**Comment by Joeper214** [comment]
どういたしまして。

**Comment by root-beer** [comment]
LGTM! Thanks. :bow:

**Pull request merged**
