### PR TITLE
Assets pipeline Bugfix

### PR DESCRIPTION
**Pull request by Joeper214**
### Goal
- bundle updated browserify-rails and changed assets config path to avoid dependency failure.

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Review and Merge PR. @root-beer  :bow:

**Comment by root-beer** [comment]
It's not working.
sprockets_error

But modify `config/application.rb`:
`config.assets.paths << "#{Rails.root}/frontend/dest/src"`
Then it works.

**Comment by Joeper214** [comment]
Have you tried it on a fresh install? eg. in an ec2 instance.

**Comment by root-beer** [comment]
Not yet. I'll try it tomorrow.

**Comment by Joeper214** [comment]
Okay. Thank you. Because I only encountered this during fresh install.

**Comment by root-beer** [comment]
Oh, I see.

**Comment by Joeper214** [comment]
Also, Please perform the update process.

```
$ npm i
$ gulp tsd
$ gulp ts
```

**Comment by root-beer** [comment]
I tried it after the update process, but it was not working.

**Comment by Joeper214** [comment]
Okay. How about fresh install? :octocat:

**Comment by root-beer** [comment]
It seems to work on fresh environment.

**Comment by Joeper214** [comment]
Yeah. That's the issue that I want to address.

**Comment by root-beer** [comment]
After fresh installation, there is no error.

**Comment by Joeper214** [comment]
Yes. Because Assets pipeline is written as new. And then there was a browserify problem. that does skips the other contents of.


`config.assets.paths << "#{Rails.root}/frontend/dest/src"`

**Comment by Joeper214** [comment]
so instead of 
'config.assets.paths << "#{Rails.root}/frontend/dest/src`

I modified it to
`config.assets.paths << "#{Rails.root}/frontend/dest/"` 
So that it could consider a much bigger scope.

**Comment by root-beer** [comment]
I see. It is Okay if I merge this?

**Comment by Joeper214** [comment]
Yeah. If you don't have any problem about it.

**Comment by root-beer** [comment]
LGTM. Thanks! @Joeper214 :bow:

**Comment by Joeper214** [comment]
:bow:

**Pull request merged**
