### PR TITLE
Refactor for ace editor

### PR DESCRIPTION
**Pull request by pocke**
https://www.npmjs.com/package/vue-ace

- [x] Replace ace to brace https://github.com/thlorenz/brace
- [x] Install vue-ace package
- [x] replace ace at serverspec-generator page
- [x] replace ace at other page
- [x] remove dependency for ace-rails-ap gem 

Update process
---------

```sh
bundle install
cd frontend
npm i

```

### CODE REVIEW

**Comment by pocke** [comment]
@Joeper214 please review and merge it :bow:

**Comment by Joeper214** [comment]
:+1: . Should I also try the production ENV for this?

**Comment by pocke** [comment]
No, It's just enough development

**Comment by Joeper214** [comment]
:+1:

**Comment by pocke** [comment]
but I think `rake assets:precompile` is faster before!

**Comment by Joeper214** [comment]
Oh. I see. maybe we can ask mr. yunoki about it?

**Comment by pocke** [comment]
yes :cat:

**Comment by Joeper214** [comment]
It seems I'm getting these errors.
brw

**Comment by Joeper214** [comment]
brw

**Comment by pocke** [comment]
Please do `update process` :bow:

```sh
bundle install
cd frontend
npm i

```

**Comment by Joeper214** [comment]
I tried these update process but still not working.

**Comment by pocke** [comment]
hmm...

**Comment by pocke** [comment]
I update package.json . please try once again

**Comment by Joeper214** [comment]
Okay. package.json updated. Thanks.!

brace

**Comment by Joeper214** [comment]
And the previous problem is fixed now. Thanks.

ace

**Comment by Joeper214** [comment]
LGTM! :cake:

**Comment by pocke** [comment]
:tada:

**Pull request merged**
