### PR TITLE
operation-notify

### PR DESCRIPTION
**Pull request by Joeper214**
### Goal

- [x]  Add user_id for operation duration table.
- [x] Use ws push notification and infralogger for start and stopping of instance.

### CODE REVIEW

**Comment by Joeper214** [comment]
Ready for review. @root-beer . Thanks!

**Comment by root-beer** [comment]
I'll review it tomorrow.

**Comment by Joeper214** [comment]
Okay. Thanks!.

**Comment by root-beer** [comment]
LGTM!

**Comment by root-beer** [comment]
merged it. Thanks!

**Comment by Joeper214** [comment]
:bow:

**Comment by Joeper214** [comment]
[WIP] next release #107

**Pull request merged**
