### PR TITLE
Fix problems in aws

### PR DESCRIPTION
**Pull request by root-beer**

### CODE REVIEW

**Comment by root-beer** [comment]
Please review and merge PR. @Joeper214 :bow:

**Comment by Joeper214** [comment]
I'll review now. Thank you!.

What is the update process for this PR?

**Comment by root-beer** [comment]
`bundle install` is needed.

**Comment by Joeper214** [comment]
```sh
[16/10/05 08:43:31.458069] [INFO]:    Rendered layouts/_notification_center.html.erb (2.3ms)
[16/10/05 08:43:31.458858] [INFO]:  Completed 200 OK in 14ms (Views: 10.1ms | ActiveRecord: 2.2ms)
[16/10/05 08:43:31.850689] [WARN]:  #<Ridley::Errors::ClientKeyFileNotFoundOrInvalid: client key is invalid or not found at: '/etc/chef/client.pem'>

[16/10/05 08:43:31.858245] [ERROR]: Actor crashed!
Ridley::Errors::ClientKeyFileNotFoundOrInvalid: client key is invalid or not found at: '/etc/chef/client.pem'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/ridley-4.2.0/lib/ridley/client.rb:144:in `initialize'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	(celluloid):0:in `remote procedure call'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/celluloid-0.16.0/lib/celluloid.rb:169:in `new'
	/app/skyhopper/vendor/bundle/ruby/2.2/gems/ridley-4.2.0/lib/ridley.rb:47:in `from_chef_config'
	/app/skyhopper/app/models/chef_api.rb:22:in `setup'
	/app/skyhopper/app/models/chef_api.rb:26:in `<module:ChefAPI>'
	/app/skyhopper/app/models/chef_api.rb:11:in `<top (required)>'
```


I encountered this error after `bundle install`

**Comment by Joeper214** [comment]
Maybe update process doesn't work. As I have test this on the AMI created by Mr. Yunoki. by checking out this branch and did the update process. Unfortunately, this error pops out. What do you think @root-beer ?

**Comment by Joeper214** [comment]
I think it's okay we base this fix to `develop` branch first. Then we will merge develop branch to `aws-marketplace` after this.

**Comment by root-beer** [comment]
Okay. I'll change the branch to `develop` based.

**Comment by Joeper214** [comment]
🙇

**Comment by root-beer** [comment]
hmm... It doesn't work on the AMI.

**Comment by Joeper214** [comment]
Yes. That's what I have encountered recently. It's because the dependencies was not override by the update. Maybe we could just suggest that It will only work during fresh install?

**Comment by root-beer** [comment]
Error of Ridley was not a problem.
Sidekiq requires Redis v2.8.0 or greater, but installed version was v2.4.10. So it didn't work on Amazon Linux.

https://github.com/mperham/sidekiq/blob/d8f11c26518dbe967880f76fd23bb99e9d2411d5/4.0-Upgrade.md

**Comment by Joeper214** [comment]
I see. Is it okay to upgrade redis?

**Comment by root-beer** [comment]
Maybe it's Okay.

**Comment by Joeper214** [comment]
Okay. Let's try and test it. :)

**Comment by root-beer** [comment]
:bow:

**Comment by root-beer** [comment]
Please review and merge PR. @Joeper214 thanks!  :bow:

**Comment by Joeper214** [comment]
Do we need to upgrade redis to test this?

**Comment by Joeper214** [comment]
Because I think we need to find a way to upgrade redis. as we have introduced `sidekiq-scheduler` feature #319.

**Comment by Joeper214** [comment]
oh sorry. I think we have to do that on another branch right?

**Comment by root-beer** [comment]
Okay. Should we change this branch to `aws-marketplace` based?

**Comment by Joeper214** [comment]
Yes I guess. Because the `sidekiq-scheduler` bug was introduced on develop. we don't want in `aws-marketplace`. Arigatou.

**Comment by Joeper214** [comment]
I'm reviewing this branch again now.

**Comment by Joeper214** [comment]
Anoher bug was encountered during installation. 😱 

```shell
[ec2-user@ip-test frontend]$ gulp tsd

/home/ec2-user/skyhopper/frontend/node_modules/gulp-sourcemaps/index.js:38
    debug(() => {return options;});
           ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ec2-user/skyhopper/frontend/node_modules/gulp-typescript/node_modules/vinyl-fs/lib/src/index.js:8:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by Joeper214** [comment]
Please let me know if you have also encountered this. 🙇

**Comment by root-beer** [comment]
Branch is ready for reviewing and merging! :bow:

**Comment by Joeper214** [comment]
I'll merge this after I review. 🙇

**Comment by Joeper214** [comment]
The redis version up and some dependency problems will be fixed in this PR #339 .

**Comment by Joeper214** [comment]
LGTM! thanks @root-beer

**Pull request merged**
