### PR TITLE
Next release version 1.8.0

### PR DESCRIPTION
**Pull request by Joeper214**
Features
-------
Keypair page improve #121 

Security Groups list Table #122 

Bug fix
-------

Fix Zabbix URL Status #127 

Version Up
--------

Bundle Update on 2015-11-25 #129 

Others
--------

Update process
----------

```sh
cd YOUR_SKYHOPPER_DIRECTORY
export RAILS_ENV=production  # This command isn't needed if you use develop environment.
git pull
git checkout <SkyHopper Version>
bundle install
cd frontend/
gulp ts
cd ..
```

### CODE REVIEW

**Comment by Joeper214** [comment]
@root-beer . Do you know why the test suddenly failed?

**Comment by root-beer** [comment]
@Joeper214 Hmm,,, I don't know.

**Comment by Joeper214** [comment]
@pocke . Do you want to release this? or some features needs to be added?

**Comment by pocke** [comment]
Release++

but test is failed...

**Comment by Joeper214** [comment]
Yes. but that's the mysterious problem right now. hmmm

**Comment by pocke** [comment]
https://github.com/skyarch-networks/skyhopper/blob/develop/.travis.yml#L5

comment outed ruby-head.

**Comment by Joeper214** [comment]
:+1:

**Comment by Joeper214** [comment]
I'll assign to you @pocke . Thanks. :bow:

**Comment by pocke** [comment]
:bow:

**Comment by Joeper214** [comment]
:tada:

**Pull request merged**
