### PR TITLE
[WIP] Serverspec Generator

### PR DESCRIPTION
**Pull request by pocke**
Goal of this PR
---------

- [ ] Create a page of serverspec generator
- [ ] Write test for code generator

### CODE REVIEW

**Comment by Joeper214** [comment]
Maybe I'll review this tommorow. :)

**Comment by pocke** [comment]
Thanks!

**Comment by pocke** [comment]
- Serverspec documentation http://serverspec.org/resource_types.html
- Import source project http://git.skyarch.net/kuwabara/sss

**Comment by Joeper214** [comment]
I think I have no problem with this PR.

**Comment by Joeper214** [comment]
I have problems on running this on my development env....

error-serverspec

**Comment by pocke** [comment]
Hmm... Please try the following commands.

```sh
$ cd frontend/
$ gulp ts
```

**Comment by Joeper214** [comment]
Sorry I'm really not that familiar with typescript. 

But I think I'm good with this PR! I'll merge it.

**Pull request merged**
