### PR TITLE
NC-624

### PR DESCRIPTION
**Pull request by root-beer**
他にもあるかも

ref: https://skyarch.backlog.jp/view/NC-624

### CODE REVIEW

**Comment by root-beer** [comment]
Please review and merge PR. @Joeper214 :bow:

**Comment by root-beer** [comment]
Let me know if you know of any better way

**Comment by Joeper214** [comment]
I think text is okay for now. to avoid XSS to browser. and it will be tagged as text only. because we don't need to render html tags on the modal

**Comment by Joeper214** [comment]
LGTM!

**Pull request merged**
