### PR TITLE
Update ridley

### PR DESCRIPTION
**Pull request by root-beer**
ref: NC-661

### Update process
```
bundle install
```

### CODE REVIEW

**Comment by root-beer** [comment]
Please review and merge PR. @Joeper214 :bow:

**Comment by Joeper214** [comment]
I'll review now

**Comment by Joeper214** [comment]
Do you know how to replicate this issue? @root-beer

**Comment by root-beer** [comment]
What do you mean? @Joeper214

**Comment by Joeper214** [comment]
Like how to test it.

**Comment by Joeper214** [comment]
Does it occurs before when you are trying to access Ec2 instance or bootstrap it using chef right?

**Comment by root-beer** [comment]
That's right.

**Comment by Joeper214** [comment]
Okay. Arigatou!

**Comment by Joeper214** [comment]
LGTM! Thanks. :bowtie:

**Comment by root-beer** [comment]
ありがとう！

**Pull request merged**
