### PR TITLE
[Hotifx] Hide JSON 

### PR DESCRIPTION
**Pull request by Joeper214**
### Objective of this PR.

Disable ajax request from saving the JSON/DATA to the browser's cache on index pages.
To avoid users from seeing the JSON Data when hitting Back or Front Button from their browsers.

### CODE REVIEW

**Comment by pocke** [comment]
I want to check this PR, but I don't know the steps to Reproduce of this bug.
Can you tell me the steps?

**Comment by Joeper214** [comment]
It is when you use the back button on your browser when going back of to your previous accessed pages of skyhopper.

Try to navigate skyhopper from clients page up to the infrastructures page. then click your back button on your browser. you will see the cached JSON on the page.


First you will see this.
infrapg

After clicking the back button, you will see this:

screenshot from 2015-09-24 12 43 14

**Comment by pocke** [comment]
Thanks! reproduced.

**Comment by pocke** [comment]
If I use the Google Chrome, this bug is happened.
However, if I use the Firefox, this bug isn't happened.

**Pull request merged**
