### PR TITLE
Bundle Update on 2017-03-03

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [activerecord-import](http://github.com/zdennis/activerecord-import), [0.16.2...0.17.1](https://github.com/zdennis/activerecord-import/compare/v0.16.2...v0.17.1)
- Updated: [arel](https://github.com/rails/arel), [6.0.3...6.0.4](https://github.com/rails/arel/compare/v6.0.3...v6.0.4) ([CHANGELOG](https://github.com/rails/arel/blob/master/History.txt))
- Updated: [aws-sdk](http://github.com/aws/aws-sdk-ruby), [2.6.42...2.8.0](https://github.com/aws/aws-sdk-ruby/compare/v2.6.42...v2.8.0) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [aws-sdk-core](http://github.com/aws/aws-sdk-ruby), [2.6.42...2.8.0](https://github.com/aws/aws-sdk-ruby/compare/v2.6.42...v2.8.0) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [aws-sdk-resources](http://github.com/aws/aws-sdk-ruby), [2.6.42...2.8.0](https://github.com/aws/aws-sdk-ruby/compare/v2.6.42...v2.8.0) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [browserify-rails](https://github.com/browserify-rails/browserify-rails), [3.4.0...4.1.0](https://github.com/browserify-rails/browserify-rails/compare/v3.4.0...v4.1.0) ([CHANGELOG](https://github.com/browserify-rails/browserify-rails/blob/master/CHANGELOG.md))
- Updated: [builder](https://github.com/jimweirich/builder), [3.2.2...3.2.3](https://github.com/jimweirich/builder/compare/builder-3.2.2...builder-3.2.3) ([CHANGELOG](https://github.com/jimweirich/builder/blob/master/CHANGES))
- Updated: [bullet](http://github.com/flyerhzm/bullet), [5.4.3...5.5.1](https://github.com/flyerhzm/bullet/compare/5.4.3...5.5.1) ([CHANGELOG](https://github.com/flyerhzm/bullet/blob/master/CHANGELOG.md))
- Updated: [chef](https://github.com/chef/chef), [12.17.44...12.19.36](https://github.com/chef/chef/compare/v12.17.44...v12.19.36) ([CHANGELOG](https://github.com/chef/chef/blob/master/CHANGELOG.md))
- Updated: [chef-config](https://github.com/chef/chef), [12.17.44...12.19.36](https://github.com/chef/chef/compare/v12.17.44...v12.19.36) ([CHANGELOG](https://github.com/chef/chef/blob/master/CHANGELOG.md))
- Updated: [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby), [1.0.3...1.0.5](https://github.com/ruby-concurrency/concurrent-ruby/compare/v1.0.3...v1.0.5) ([CHANGELOG](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/CHANGELOG.md))
- Updated: [coveralls](https://github.com/lemurheavy/coveralls-ruby), [0.8.17...0.8.19](https://github.com/lemurheavy/coveralls-ruby/compare/v0.8.17...v0.8.19) ([CHANGELOG](https://github.com/lemurheavy/coveralls-ruby/blob/master/CHANGELOG.md))
- Updated: [diff-lcs](https://github.com/halostatue/diff-lcs), [1.2.5...1.3](https://github.com/halostatue/diff-lcs/compare/v1.2.5...v1.3) ([CHANGELOG](https://github.com/halostatue/diff-lcs/blob/master/History.md))
- Updated: [ffi](http://github.com/ffi/ffi), [1.9.14...1.9.17](https://github.com/ffi/ffi/compare/1.9.14...1.9.17)
- Updated: [foreman](http://github.com/ddollar/foreman), [0.82.0...0.83.0](https://github.com/ddollar/foreman/compare/v0.82.0...v0.83.0) ([CHANGELOG](https://github.com/ddollar/foreman/blob/master/Changelog.md))
- Updated: [github-markup](https://github.com/github/markup), [1.4.0...1.4.1](https://github.com/github/markup/compare/v1.4.0...v1.4.1) ([CHANGELOG](https://github.com/github/markup/blob/master/HISTORY.md))
- Updated: [guard](https://github.com/guard/guard), [2.14.0...2.14.1](https://github.com/guard/guard/compare/v2.14.0...v2.14.1) ([CHANGELOG](https://github.com/guard/guard/blob/master/CHANGELOG.md))
- Updated: [jbuilder](https://github.com/rails/jbuilder), [2.6.1...2.6.3](https://github.com/rails/jbuilder/compare/v2.6.1...v2.6.3) ([CHANGELOG](https://github.com/rails/jbuilder/blob/master/CHANGELOG.md))
- Updated: [json](http://github.com/flori/json), [1.8.3...1.8.6](https://github.com/flori/json/compare/v1.8.3...v1.8.6) ([CHANGELOG](https://github.com/flori/json/blob/master/CHANGES))
- Updated: [kaminari](https://github.com/amatsuda/kaminari), [0.17.0...1.0.1](https://github.com/amatsuda/kaminari/compare/v0.17.0...v1.0.1) ([CHANGELOG](https://github.com/amatsuda/kaminari/blob/master/CHANGELOG.rdoc))
- Updated: [knife-windows](https://github.com/chef/knife-windows), [1.8.0...1.9.0](https://github.com/chef/knife-windows/compare/v1.8.0...v1.9.0) ([CHANGELOG](https://github.com/chef/knife-windows/blob/master/CHANGELOG.md))
- Updated: [lumberjack](http://github.com/bdurand/lumberjack), [1.0.10...1.0.11](https://github.com/bdurand/lumberjack/compare/v1.0.10...v1.0.11) ([CHANGELOG](https://github.com/bdurand/lumberjack/blob/master/CHANGES.txt))
- Updated: mixlib-archive, 0.2.0...0.4.1
- Updated: [net-ssh](https://github.com/net-ssh/net-ssh), [3.2.0...4.1.0](https://github.com/net-ssh/net-ssh/compare/v3.2.0...v4.1.0) ([CHANGELOG](https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt))
- Updated: [net-ssh-gateway](https://github.com/net-ssh/net-scp), [1.2.0...2.0.0](https://github.com/net-ssh/net-scp/compare/v1.2.0...v2.0.0) ([CHANGELOG](https://github.com/net-ssh/net-scp/blob/master/CHANGES.txt))
- Updated: [nio4r](https://github.com/celluloid/nio4r), [1.2.1...2.0.0](https://github.com/celluloid/nio4r/compare/v1.2.1...v2.0.0) ([CHANGELOG](https://github.com/celluloid/nio4r/blob/master/CHANGES.md))
- Updated: [nokogiri](https://github.com/sparklemotion/nokogiri), [1.6.8.1...1.7.0.1](https://github.com/sparklemotion/nokogiri/compare/v1.6.8.1...v1.7.0.1) ([CHANGELOG](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md))
- Updated: [ohai](https://github.com/chef/ohai), [8.22.1...8.23.0](https://github.com/chef/ohai/compare/v8.22.1...v8.23.0) ([CHANGELOG](https://github.com/chef/ohai/blob/master/CHANGELOG.md))
- Updated: [parser](https://github.com/whitequark/parser), [2.3.3.1...2.4.0.0](https://github.com/whitequark/parser/compare/v2.3.3.1...v2.4.0.0) ([CHANGELOG](https://github.com/whitequark/parser/blob/master/CHANGELOG.md))
- Updated: [pry-doc](https://github.com/pry/pry-doc), [0.9.0...0.10.0](https://github.com/pry/pry-doc/compare/v0.9.0...v0.10.0) ([CHANGELOG](https://github.com/pry/pry-doc/blob/master/CHANGELOG.md))
- Updated: [pry-rails](https://github.com/rweng/pry-rails), [0.3.4...0.3.5](https://github.com/rweng/pry-rails/compare/v0.3.4...v0.3.5)
- Updated: [public_suffix](http://github.com/weppos/publicsuffix-ruby), [2.0.4...2.0.5](https://github.com/weppos/publicsuffix-ruby/compare/v2.0.4...v2.0.5) ([CHANGELOG](https://github.com/weppos/publicsuffix-ruby/blob/master/CHANGELOG.md))
- Updated: [rails-dom-testing](https://github.com/rails/rails-dom-testing), [1.0.7...1.0.8](https://github.com/rails/rails-dom-testing/compare/v1.0.7...v1.0.8)
- Updated: [rainbow](https://github.com/sickill/rainbow), [2.1.0...2.2.1](https://github.com/sickill/rainbow/compare/v2.1.0...v2.2.1) ([CHANGELOG](https://github.com/sickill/rainbow/blob/master/Changelog.md))
- Updated: [rb-inotify](http://github.com/nex3/rb-inotify), [0.9.7...0.9.8](https://github.com/nex3/rb-inotify/compare/v0.9.7...v0.9.8)
- Updated: [redcarpet](http://github.com/vmg/redcarpet), [3.3.4...3.4.0](https://github.com/vmg/redcarpet/compare/v3.3.4...v3.4.0) ([CHANGELOG](https://github.com/vmg/redcarpet/blob/master/CHANGELOG.md))
- Updated: [redis](https://github.com/redis/redis-rb), [3.3.2...3.3.3](https://github.com/redis/redis-rb/compare/v3.3.2...v3.3.3) ([CHANGELOG](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md))
- Updated: [redis-namespace](http://github.com/resque/redis-namespace), [1.5.2...1.5.3](https://github.com/resque/redis-namespace/compare/v1.5.2...v1.5.3) ([CHANGELOG](https://github.com/resque/redis-namespace/blob/master/CHANGELOG.md))
- Updated: [rubocop](http://github.com/bbatsov/rubocop), [0.46.0...0.47.1](https://github.com/bbatsov/rubocop/compare/v0.46.0...v0.47.1) ([CHANGELOG](https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md))
- Updated: [rufus-scheduler](http://github.com/jmettraux/rufus-scheduler), [3.3.1...3.3.4](https://github.com/jmettraux/rufus-scheduler/compare/v3.3.1...v3.3.4) ([CHANGELOG](https://github.com/jmettraux/rufus-scheduler/blob/master/CHANGELOG.txt))
- Updated: [serverspec](https://github.com/mizzy/serverspec), [2.37.2...2.38.0](https://github.com/mizzy/serverspec/compare/v2.37.2...v2.38.0) ([CHANGELOG](https://github.com/mizzy/serverspec/releases))
- Updated: [sidekiq](https://github.com/mperham/sidekiq), [4.2.7...4.2.9](https://github.com/mperham/sidekiq/compare/v4.2.7...v4.2.9) ([CHANGELOG](https://github.com/mperham/sidekiq/blob/master/Changes.md))
- Updated: [sinatra](http://github.com/sinatra/sinatra), [1.4.7...1.4.8](https://github.com/sinatra/sinatra/compare/v1.4.7...v1.4.8) ([CHANGELOG](https://github.com/sinatra/sinatra/blob/master/CHANGES))
- Updated: [specinfra](https://github.com/mizzy/specinfra), [2.66.3...2.67.2](https://github.com/mizzy/specinfra/compare/v2.66.3...v2.67.2)
- Updated: [spring](https://github.com/rails/spring), [2.0.0...2.0.1](https://github.com/rails/spring/compare/v2.0.0...v2.0.1) ([CHANGELOG](https://github.com/rails/spring/blob/master/CHANGELOG.md))
- Updated: [sqlite3](https://github.com/sparklemotion/sqlite3-ruby), [1.3.12...1.3.13](https://github.com/sparklemotion/sqlite3-ruby/compare/v1.3.12...v1.3.13) ([CHANGELOG](https://github.com/sparklemotion/sqlite3-ruby/blob/master/API_CHANGES.rdoc))
- Updated: [term-ansicolor](http://github.com/flori/term-ansicolor), [1.3.2...1.4.0](https://github.com/flori/term-ansicolor/compare/v1.3.2...v1.4.0) ([CHANGELOG](https://github.com/flori/term-ansicolor/blob/master/CHANGES))
- Updated: [therubyracer](http://github.com/cowboyd/therubyracer), [0.12.2...0.12.3](https://github.com/cowboyd/therubyracer/compare/v0.12.2...v0.12.3) ([CHANGELOG](https://github.com/cowboyd/therubyracer/blob/master/Changelog.md))
- Updated: [thread_safe](https://github.com/ruby-concurrency/thread_safe), [0.3.5...0.3.6](https://github.com/ruby-concurrency/thread_safe/compare/v0.3.5...v0.3.6)
- Updated: [tilt](http://github.com/rtomayko/tilt), [2.0.5...2.0.6](https://github.com/rtomayko/tilt/compare/v2.0.5...v2.0.6) ([CHANGELOG](https://github.com/rtomayko/tilt/blob/master/CHANGELOG.md))
- Updated: [tins](https://github.com/flori/tins), [1.13.0...1.13.2](https://github.com/flori/tins/compare/v1.13.0...v1.13.2)
- Updated: [uglifier](http://github.com/lautis/uglifier), [3.0.4...3.1.3](https://github.com/lautis/uglifier/compare/v3.0.4...v3.1.3) ([CHANGELOG](https://github.com/lautis/uglifier/blob/master/CHANGELOG.md))
- Updated: [unicode-display_width](http://github.com/janlelis/unicode-display_width), [1.1.2...1.1.3](https://github.com/janlelis/unicode-display_width/compare/v1.1.2...v1.1.3) ([CHANGELOG](https://github.com/janlelis/unicode-display_width/blob/master/CHANGELOG.txt))
- Updated: [warden](http://github.com/hassox/warden), [1.2.6...1.2.7](https://github.com/hassox/warden/compare/v1.2.6...v1.2.7) ([CHANGELOG](https://github.com/hassox/warden/blob/master/History.rdoc))
- Updated: [winrm](https://github.com/WinRb/WinRM), [2.1.1...2.1.3](https://github.com/WinRb/WinRM/compare/v2.1.1...v2.1.3) ([CHANGELOG](https://github.com/WinRb/WinRM/blob/master/changelog.md))
- Updated: [yard](http://github.com/lsegal/yard), [0.9.5...0.9.8](https://github.com/lsegal/yard/compare/v0.9.5...v0.9.8) ([CHANGELOG](https://github.com/lsegal/yard/blob/master/CHANGELOG.md))
- Added: [kaminari-actionview](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Added: [kaminari-activerecord](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)
- Added: [kaminari-core](https://github.com/amatsuda/kaminari), [1.0.1](https://github.com/amatsuda/kaminari/tree/v1.0.1)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
61 Pull Requests sent and 7 hours, 12 minutes, and 26 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by Joeper214** [comment]
A lot of updates. 😨

**Comment by root-beer** [comment]
🙀

**Comment by Joeper214** [comment]
I guess I need to test this first before merging it into `develop` branch. がんばります。

**Comment by Joeper214** [comment]
Seems no problem after fresh install on EC2 server. I'll merge this.

**Pull request merged**
