### PR TITLE
Bundle Update on 2016-01-06

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [aws-sdk](http://github.com/aws/aws-sdk-ruby), [2.2.8...2.2.9](https://github.com/aws/aws-sdk-ruby/compare/v2.2.8...v2.2.9) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [aws-sdk-core](http://github.com/aws/aws-sdk-ruby), [2.2.8...2.2.9](https://github.com/aws/aws-sdk-ruby/compare/v2.2.8...v2.2.9) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [aws-sdk-resources](http://github.com/aws/aws-sdk-ruby), [2.2.8...2.2.9](https://github.com/aws/aws-sdk-ruby/compare/v2.2.8...v2.2.9) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [bullet](http://github.com/flyerhzm/bullet), [4.14.10...5.0.0](https://github.com/flyerhzm/bullet/compare/4.14.10...5.0.0) ([CHANGELOG](https://github.com/flyerhzm/bullet/blob/master/CHANGELOG.md))
- Updated: [httpclient](https://github.com/nahi/httpclient), [2.7.0.1...2.7.1](https://github.com/nahi/httpclient/compare/v2.7.0.1...v2.7.1) ([CHANGELOG](https://github.com/nahi/httpclient/blob/master/CHANGELOG.md))
- Updated: [ipaddress](http://github.com/bluemonk/ipaddress), [0.8.0...0.8.2](https://github.com/bluemonk/ipaddress/compare/v0.8.0...v0.8.2) ([CHANGELOG](https://github.com/bluemonk/ipaddress/blob/master/CHANGELOG.rdoc))
- Updated: [knife-windows](https://github.com/chef/knife-windows), [1.1.2...1.1.3](https://github.com/chef/knife-windows/compare/v1.1.2...v1.1.3) ([CHANGELOG](https://github.com/chef/knife-windows/blob/master/CHANGELOG.md))
- Updated: [lumberjack](http://github.com/bdurand/lumberjack), [1.0.9...1.0.10](https://github.com/bdurand/lumberjack/compare/v1.0.9...v1.0.10) ([CHANGELOG](https://github.com/bdurand/lumberjack/blob/master/CHANGES.txt))
- Updated: [rqrcode](https://github.com/whomwah/rqrcode), [0.8.0...0.9.0](https://github.com/whomwah/rqrcode/compare/v0.8.0...v0.9.0) ([CHANGELOG](https://github.com/whomwah/rqrcode/blob/master/CHANGELOG))
- Updated: [tilt](http://github.com/rtomayko/tilt), [2.0.1...2.0.2](https://github.com/rtomayko/tilt/compare/v2.0.1...v2.0.2) ([CHANGELOG](https://github.com/rtomayko/tilt/blob/master/CHANGELOG.md))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Dependency Updates
7 Pull Requests sent and 7 minutes, and 9 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by Joeper214** [comment]
reekfailed


SIdeCI reek failed.

**Comment by pocke** [comment]
I think it's reek's bug.

**Comment by pocke** [comment]
I'll fix this bug. 
If this PR doesn't have other bugs, merging is ok!

**Comment by Joeper214** [comment]
Thanks for reporting it to reek repo.

**Comment by pocke** [comment]
LGTM

**Pull request merged**
