### PR TITLE
Serverspec gen external

### PR DESCRIPTION
**Pull request by pocke**
- [x] Move files to [skyarch-networks/serverspec-generator](https://github.com/skyarch-networks/serverspec-generator)

### Update process

```sh
cd frontend
npm i
gulp tsd
gulp ts
```

### CODE REVIEW

**Comment by pocke** [comment]
@Joeper214 please review and merge it :bow:

**Comment by Joeper214** [comment]
What's the update process for this? @pocke

**Comment by pocke** [comment]
@Joeper214 I wrote update process in summary of PR.

**Comment by Joeper214** [comment]
Thanks.

**Comment by Joeper214** [comment]
I think ace stopped working here? 
ace

**Comment by pocke** [comment]
Hmm... ace isn't dead in my environment...

**Comment by Joeper214** [comment]
Okay. I'll try to bundle install again.

**Comment by pocke** [comment]
thanks :bow:

**Comment by Joeper214** [comment]
hmm... 
screenshot from 2015-12-10 14 24 36

**Comment by Joeper214** [comment]
Also, 
sss

**Comment by pocke** [comment]
ok, I'll Investigation this error

**Comment by Joeper214** [comment]
Thanks. :bow:

**Comment by Joeper214** [comment]
I'll try to install this also. https://github.com/vuejs/vue-devtools

**Comment by pocke** [comment]
I can't reproduce this error...

**Comment by Joeper214** [comment]
What vue.js version are you using? @pocke

**Comment by Joeper214** [comment]
because I use. "vue": "~1.0.7",

**Comment by pocke** [comment]
maybe I use Vue 1.0.11

**Comment by Joeper214** [comment]
Okay. I'll update mine.

**Comment by Joeper214** [comment]
Okay. maybe @root-beer . can try on his instance if this also happens? what do you think @pocke ?. If not, then. LGTM!.

**Comment by root-beer** [comment]
LGTM! :+1:

**Comment by Joeper214** [comment]
Thanks. @root-beer . I'll merge PR.

**Pull request merged**
