### PR TITLE
NC-619

### PR DESCRIPTION
**Pull request by Joeper214**
ref: https://skyarch.backlog.jp/view/NC-619

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Review and merge PR. @root-beer

**Comment by root-beer** [comment]
I'll review now.

**Comment by root-beer** [comment]
Do you mind if I correct the japanese locale?

**Comment by Joeper214** [comment]
はい。おねがいします。

**Comment by root-beer** [comment]
Thanks. LGTM!

**Comment by Joeper214** [comment]
:bow:

**Pull request merged**
