### PR TITLE
support for  windows

### PR DESCRIPTION
**Pull request by Joeper214**
Started to add support for windows in skyhopper.

## Goal
- [x] Create Windows Cloudformation template 
- [x] Update all ami mappings on amazon linux and windows ec2
- [x] able to bootstrap windows instance using knife-windows with winrm connection
- [x] Update test 

refs:

 - https://skyarch.backlog.jp/view/NC-596 
 - https://skyarch.backlog.jp/view/NC-434

Update process
----------

```sh
cd YOUR_SKYHOPPER_DIRECTORY
export RAILS_ENV=production  # This command isn't needed if you use develop environment.
git pull
bundle install
bundle exec rake db:migrate
bundle exec rake db:seed
```

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Review and Merge PR. @root-beer

**Comment by root-beer** [comment]
I'll review now.

**Comment by Joeper214** [comment]
:bow:

**Comment by root-beer** [comment]
LGTM. Thanks! @Joeper214 :bow:

**Comment by Joeper214** [comment]
ありがとう。

**Pull request merged**
