### PR TITLE
MySQL gem downgrade to 0.3.20

### PR DESCRIPTION
**Pull request by pocke**
- http://stackoverflow.com/questions/32457657/rails-4-gemloaderror-specified-mysql2-for-database-adapter-but-the-gem-i
- https://github.com/brianmario/mysql2/issues/675

### CODE REVIEW

**Comment by pocke** [comment]
@Joeper214  please merge it

**Comment by Joeper214** [comment]
:+1:    Error also encountered. and fixed by downgrading.

**Comment by pocke** [comment]
Maybe, cause of your problem is this...

**Comment by Joeper214** [comment]
Merged thanks!

**Comment by pocke** [comment]
Thanks!

**Pull request merged**
