### PR TITLE
NC-602

### PR DESCRIPTION
**Pull request by Joeper214**
ref: https://skyarch.backlog.jp/view/NC-602.

Fix issues on the following pages.

1. Client index page button authorization
2. Project index page button authorization
3. Infrastructures index pag button authorization

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Review and Merge PR. @pocke

**Comment by pocke** [comment]
I'll review this PR now :cat2:

**Comment by Joeper214** [comment]
Please be reminded that #188 is in related to this.

**Comment by pocke** [comment]
OK, should I merge these PRs at the same time ?

**Comment by pocke** [comment]
LGTM! :100:

**Comment by pocke** [comment]
I think we should refactor https://github.com/skyarch-networks/skyhopper/blob/master/app/assets/javascripts/modules/listen.js .
Because it isn't DRY. There is the same HTML code under `app/views`.

**Comment by Joeper214** [comment]
Hmmm... Yes, Iv'e been thinking about that. do you have any suggestions?

**Comment by pocke** [comment]
- http://vuejs.org/guide/components.html
- http://vuejs.org/guide/application.html

In the Vue way, we should use vueify. https://github.com/vuejs/vueify

**Pull request merged**
