### PR TITLE
Applied SSP for cf_templates indexpage.

### PR DESCRIPTION
**Pull request by Joeper214**
### Cloud Formation Templates Indexpage

* Sorting
* Searching
* Pagination

Please Merge PR after reviewing. Thanks!

### CODE REVIEW

**Comment by pocke** [comment]
I'll merge it after merging #34 .
I investigate the cause of failing test of #34 .

**Comment by Joeper214** [comment]
:+1:  Thanks!

**Comment by Joeper214** [comment]
There are conflicts. I'll fix this.

**Comment by pocke** [comment]
I can't merge on GitHub ...
Can you resolve conflict manually ?

**Comment by pocke** [comment]
Thanks

**Comment by pocke** [comment]
Thanks!

**Pull request merged**
