### PR TITLE
Use spring in rails only

### PR DESCRIPTION
**Pull request by root-beer**
Sidekiq Jobs does not work well when using spring in Sidekiq.

### CODE REVIEW

**Comment by skyarch-networks** [comment]
Click here if you want to create rubocop's auto-correct Pull Request 

https://www.sideci.com/github_repositories/31754199/auto_correct/rubocop/pull_request/209/branch/use-spring-rails-only

**Comment by root-beer** [comment]
Auto-correctable file didn't exist on this Pull Request from [SideCI](https://www.sideci.com/).

**Comment by root-beer** [comment]
Click here if you want to create rubocop's auto-correct Pull Request 

https://www.sideci.com/github_repositories/31754199/auto_correct/rubocop/pull_request/209/branch/use-spring-rails-only

**Comment by Joeper214** [comment]
Auto-correctable file didn't exist on this Pull Request from [SideCI](https://www.sideci.com/).

**Comment by pocke** [comment]
In another project, I also have problem like this.
Do you have any solution for the issue?

**Comment by Joeper214** [comment]
Hmmmm... Sorry but I don't have right now. maybe @root-beer  Is looking a solution?

**Comment by root-beer** [comment]
I don't have any solution for the issue.
So I think we shouldn't use spring in sidekiq.

**Comment by Joeper214** [comment]
:+1:

**Pull request merged**
