### PR TITLE
Keypair improve

### PR DESCRIPTION
**Pull request by Joeper214**
ref: https://skyarch.backlog.jp/view/NC-422

### Goal 
Improvement of keypair management

- [x] Pagination
- [x] Searching

Please review and Merge PR: @root-beer . :bow:

### CODE REVIEW

**Comment by root-beer** [comment]
Page 1 is empty and strange.

kp1
kp2

**Comment by Joeper214** [comment]
Okay. I'll check it out. thanks.

**Comment by Joeper214** [comment]
I don't know the cause of this. but it seems to be working fine with me.

Did you tried `git pull keypair-imp`?

working



wwd

**Comment by root-beer** [comment]
Hmm.., When a key exists in more than one region, that seems to occur.

**Comment by Joeper214** [comment]
Oh . I see. I'll try to replicate it again. thanks.

**Comment by Joeper214** [comment]
I saw the problem but. I don't know how to fix it yet. It has something to do with the `v-show="is_selected(key_pair.region)"` function that filters the contents of the table.

**Comment by root-beer** [comment]
Hmm,,, I'll consider about that later.

**Comment by Joeper214** [comment]
Okay thanks.

**Comment by Joeper214** [comment]
I think I found a solution and pushed it. Will it be okay @root-beer ?

**Comment by Joeper214** [comment]
I also push a fix when switching region I reset the page to 1.

**Comment by root-beer** [comment]
Thanks!
I'll review it.

**Comment by root-beer** [comment]
LGTM!

**Comment by Joeper214** [comment]
Thanks!. :bow:

**Comment by root-beer** [comment]
Merged it. Thanks :bow:

**Pull request merged**
