### PR TITLE
In cook, use Project Parameter

### PR DESCRIPTION
**Pull request by pocke**
Goal
-------

- [x] Client-side
- [x] server-side
- [x] escape as HTML

### CODE REVIEW

**Comment by pocke** [comment]
Usage
-------

Click the following button, 




Input `${`




Preventive measures for XSS
--------




Update process
--------

```sh
$ git pull
$ cd frontend
$ gulp ts
```

**Comment by pocke** [comment]
@Joeper214 please review and merge it!

**Comment by Joeper214** [comment]
I'll review now.

**Comment by Joeper214** [comment]
LGTM!

**Comment by pocke** [comment]
Thanks!

**Pull request merged**
