### PR TITLE
Bundle Update on 2015-12-23

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [ast](https://github.com/whitequark/ast), [2.1.0...2.2.0](https://github.com/whitequark/ast/compare/v2.1.0...v2.2.0) ([CHANGELOG](https://github.com/whitequark/ast/blob/master/CHANGELOG.md))
- Updated: [aws-sdk](http://github.com/aws/aws-sdk-ruby), [2.2.6...2.2.8](https://github.com/aws/aws-sdk-ruby/compare/v2.2.6...v2.2.8) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [aws-sdk-core](http://github.com/aws/aws-sdk-ruby), [2.2.6...2.2.8](https://github.com/aws/aws-sdk-ruby/compare/v2.2.6...v2.2.8) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [aws-sdk-resources](http://github.com/aws/aws-sdk-ruby), [2.2.6...2.2.8](https://github.com/aws/aws-sdk-ruby/compare/v2.2.6...v2.2.8) ([CHANGELOG](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md))
- Updated: [chef](https://github.com/chef/chef), [12.5.1...12.6.0](https://github.com/chef/chef/compare/v12.5.1...v12.6.0) ([CHANGELOG](https://github.com/chef/chef/blob/master/CHANGELOG.md))
- Updated: [chef-config](https://github.com/chef/chef), [12.5.1...12.6.0](https://github.com/chef/chef/compare/v12.5.1...v12.6.0) ([CHANGELOG](https://github.com/chef/chef/blob/master/CHANGELOG.md))
- Updated: [coffee-rails](https://github.com/rails/coffee-rails), [4.1.0...4.1.1](https://github.com/rails/coffee-rails/compare/v4.1.0...v4.1.1) ([CHANGELOG](https://github.com/rails/coffee-rails/blob/master/CHANGELOG.md))
- Updated: [nio4r](https://github.com/celluloid/nio4r), [1.1.1...1.2.0](https://github.com/celluloid/nio4r/compare/v1.1.1...v1.2.0) ([CHANGELOG](https://github.com/celluloid/nio4r/blob/master/CHANGES.md))
- Updated: [nokogiri](https://github.com/sparklemotion/nokogiri), [1.6.7...1.6.7.1](https://github.com/sparklemotion/nokogiri/compare/v1.6.7...v1.6.7.1) ([CHANGELOG](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.ja.rdoc))
- Updated: [rdoc](https://github.com/rdoc/rdoc), [4.2.0...4.2.1](https://github.com/rdoc/rdoc/compare/v4.2.0...v4.2.1) ([CHANGELOG](https://github.com/rdoc/rdoc/blob/master/History.rdoc))
- Updated: [responders](http://github.com/plataformatec/responders), [2.1.0...2.1.1](https://github.com/plataformatec/responders/compare/v2.1.0...v2.1.1) ([CHANGELOG](https://github.com/plataformatec/responders/blob/master/CHANGELOG.md))
- Updated: [rqrcode](https://github.com/whomwah/rqrcode), [0.7.0...0.8.0](https://github.com/whomwah/rqrcode/compare/v0.7.0...v0.8.0) ([CHANGELOG](https://github.com/whomwah/rqrcode/blob/master/CHANGELOG))
- Updated: [sprockets-rails](https://github.com/rails/sprockets-rails), [2.3.3...3.0.0](https://github.com/rails/sprockets-rails/compare/v2.3.3...v3.0.0)
- Added: [proxifier](https://github.com/samuelkadolph/ruby-proxifier), [1.0.3](https://github.com/samuelkadolph/ruby-proxifier/tree/v1.0.3)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Dependency Updates
5 Pull Requests sent and 4 minutes, and 46 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by Joeper214** [comment]
Test is broken.

**Comment by pocke** [comment]
:scream_cat:

**Comment by pocke** [comment]
I'll fix it

**Comment by pocke** [comment]
https://github.com/metaskills/less-rails/pull/112

**Comment by Joeper214** [comment]
I see. Maybe sprockets3 is still not needed to be updated? because is still has bug.

**Comment by pocke** [comment]
I think we don't need less-rails (and sass-rails). Because we don't use less/sass

**Comment by pocke** [comment]
We use sass as compressor https://github.com/skyarch-networks/skyhopper/blob/develop/config/environments/production.rb#L28

**Comment by Joeper214** [comment]
:+1:

**Comment by pocke** [comment]
Rails server died on this branch...

**Comment by pocke** [comment]
https://github.com/brentd/xray-rails/pull/62

**Comment by pocke** [comment]
Hmm... sprockets-rails 3.0 is buggy...

**Comment by Joeper214** [comment]
yes. still needs to be improved. maybe we can use/checkout it next month?

**Comment by pocke** [comment]
Yes, I'll fix sprocket version.

**Comment by Joeper214** [comment]
:bow:

**Pull request merged**
