### PR TITLE
NC-495

### PR DESCRIPTION
**Pull request by Joeper214**
For https://skyarch.backlog.jp/view/NC-495. 

added disabled boostrap button when ec2 has stopped. and added I18n

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Review and Merge PR. Thanks. @pocke

**Comment by pocke** [comment]
LGTM!


pen
stop


but I think button should be disabled  if status is `stopping` or `pending`. 
Please change `disabled: stopped` to `disabled: !running`?

**Comment by Joeper214** [comment]
:ok_hand:

**Comment by pocke** [comment]
Thanks!

**Pull request merged**
