### PR TITLE
Vpc private addr

### PR DESCRIPTION
**Pull request by pocke**
Ref: #67, #75 

I fixed problem by 9a90318797aef9837c9d721e81ed55d2424d7fa1 .

### CODE REVIEW

**Comment by pocke** [comment]
@Joeper214 please review and merge it :bow:

**Comment by Joeper214** [comment]
Thanks!. :bow:

**Comment by Joeper214** [comment]
I think the test is failed..  @pocke

**Comment by pocke** [comment]
```
  1) Users::SessionsController#check_mfa_key when receive email, password and MFA-token when verify success should be success

     Failure/Error: expect(response).to be_success,

       expected success, but response code is 302, response body is "<html><body>You are being <a href=\"http://test.host/users/sign_in?lang=ja\">redirected</a>.</body></html>"

     # ./spec/support/controller_macros.rb:35:in `block in should_be_success'
```

**Comment by pocke** [comment]
I retry test

**Comment by Joeper214** [comment]
LGTM!.

**Pull request merged**
