### PR TITLE
Security Groups Edit

### PR DESCRIPTION
**Pull request by Joeper214**
Next Goal for #122 

### Goal
- [x] Change security modal and table
- [x] Get available and selected security groups
- [x] Modify security groups based on selection
- [x] iT18N

### CODE REVIEW

**Comment by Joeper214** [comment]
Please Review and Merge PR: @root-beer . Thanks. :bow:

**Comment by root-beer** [comment]
:+1:

**Comment by Joeper214** [comment]
Thanks. :bow:

**Comment by root-beer** [comment]
Thanks :bow:

**Pull request merged**
