### PR TITLE
Detect Browser

### PR DESCRIPTION
**Pull request by Joeper214**
Please Review and Merge PR. @root-beer  🙇

### CODE REVIEW

**Comment by root-beer** [comment]
I'll review it now.

**Comment by root-beer** [comment]
Would you mind if I rephrase Japanese locales?

**Comment by Joeper214** [comment]
Yes please.

**Comment by root-beer** [comment]
LGTM. Thanks! 🙇

**Comment by Joeper214** [comment]
🙇

**Pull request merged**
