### PR TITLE
[WIP]Use spring.

### PR DESCRIPTION
**Pull request by pocke**
Goal
------

- [x] Install spring gem
- [x] do `bundle exec spring binstub --all`
  - [x] standard commands
  - [x] rspec
  - [x] sidekiq
  - [ ] crono

What's spring?
---------

Spring is a Rails application preloader.

[rails/spring: Rails application preloader](https://github.com/rails/spring)

How to use?
---------

When we use some commands, we should use `bin/foo` instead of `bundle exec foo`.

### CODE REVIEW

**Comment by pocke** [comment]
@root-beer レビューとマージをお願いします :bow:

**Comment by pocke** [comment]
crono はspringで使うためのGemが見当たらなかったので、とりあえず無視しました。
`bin/rails c`や`bin/rake`, `bin/rspec`などははやくなっています。

**Comment by pocke** [comment]
In candy PC, Spring doesn't work...
@Joeper214 please try this branch?

Ref: https://github.com/rails/spring/issues/456

**Comment by Joeper214** [comment]
:+1:

**Comment by Joeper214** [comment]
do I have to execute this `bundle exec spring binstub --all`?

**Comment by pocke** [comment]
No, I think you should not do this command.

**Comment by pocke** [comment]
```sh
bundle install
./scripts/dev_server.sh
# or
bin/rake routes
# or
bin/rspec
# or 
bin/rails c
```

**Comment by Joeper214** [comment]
I got the same error with https://github.com/rails/spring/issues/456

**Comment by pocke** [comment]
Hmm... candy got same error.

**Comment by Joeper214** [comment]
spring-err

**Comment by pocke** [comment]
I think the PR should be pending.

**Comment by Joeper214** [comment]
I guess so. Because I think https://github.com/rails/spring/issues/456 is not yet done.

**Comment by pocke** [comment]
I have changed the title.

**Comment by Joeper214** [comment]
@pocke . The problem is how fxied. https://github.com/rails/spring/issues/456#issuecomment-180078281

**Comment by pocke** [comment]
:tada: :tada: :tada: :tada: 
Please try this PR and merge it :bow:

**Comment by Joeper214** [comment]
@pocke . I tried this PR. but it has a redirect error. As shown below.

redirect_err

**Comment by Joeper214** [comment]
I think its working now. I just merged the develop branch into this branch.  :tada:

**Comment by Joeper214** [comment]
Can you verify if it's working on your PC? @root-beer . :bow:

**Comment by root-beer** [comment]
It seems to work on my environment.

**Comment by Joeper214** [comment]
Okay. I'll merge this. Thanks!.

**Comment by pocke** [comment]
さいこう

**Pull request merged**
